"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ObjectId = exports.propRefArray = exports.propRef = exports.index = exports.propArray = exports.post = exports.pre = exports.model = exports.BaseCrudManager = exports.BaseCrudItem = exports.prop = exports.schema = exports.Schema = exports.MongoModule = exports.method = exports.virtual = exports.staticMethod = exports.ModelRepository = void 0;
const appolo_mongo_1 = require("appolo-mongo");
Object.defineProperty(exports, "Schema", { enumerable: true, get: function () { return appolo_mongo_1.Schema; } });
Object.defineProperty(exports, "schema", { enumerable: true, get: function () { return appolo_mongo_1.schema; } });
Object.defineProperty(exports, "prop", { enumerable: true, get: function () { return appolo_mongo_1.prop; } });
Object.defineProperty(exports, "staticMethod", { enumerable: true, get: function () { return appolo_mongo_1.staticMethod; } });
Object.defineProperty(exports, "virtual", { enumerable: true, get: function () { return appolo_mongo_1.virtual; } });
Object.defineProperty(exports, "method", { enumerable: true, get: function () { return appolo_mongo_1.method; } });
Object.defineProperty(exports, "pre", { enumerable: true, get: function () { return appolo_mongo_1.pre; } });
Object.defineProperty(exports, "post", { enumerable: true, get: function () { return appolo_mongo_1.post; } });
Object.defineProperty(exports, "index", { enumerable: true, get: function () { return appolo_mongo_1.index; } });
Object.defineProperty(exports, "propArray", { enumerable: true, get: function () { return appolo_mongo_1.propArray; } });
Object.defineProperty(exports, "propRef", { enumerable: true, get: function () { return appolo_mongo_1.propRef; } });
Object.defineProperty(exports, "propRefArray", { enumerable: true, get: function () { return appolo_mongo_1.propRefArray; } });
Object.defineProperty(exports, "ObjectId", { enumerable: true, get: function () { return appolo_mongo_1.ObjectId; } });
const decorator_1 = require("./module/src/decorator");
Object.defineProperty(exports, "model", { enumerable: true, get: function () { return decorator_1.model; } });
const mongoModule_1 = require("./module/mongoModule");
Object.defineProperty(exports, "MongoModule", { enumerable: true, get: function () { return mongoModule_1.MongoModule; } });
const modelRepository_1 = require("./module/src/modelRepository");
Object.defineProperty(exports, "ModelRepository", { enumerable: true, get: function () { return modelRepository_1.ModelRepository; } });
const baseCrudManager_1 = require("./module/src/baseCrudManager");
Object.defineProperty(exports, "BaseCrudManager", { enumerable: true, get: function () { return baseCrudManager_1.BaseCrudManager; } });
const baseCrudItem_1 = require("./module/src/baseCrudItem");
Object.defineProperty(exports, "BaseCrudItem", { enumerable: true, get: function () { return baseCrudItem_1.BaseCrudItem; } });
exports.mongoose = require("mongoose");
//# sourceMappingURL=index.js.map